### ISSUE TITLE
Reduce precision

### ISSUE THREAD

**Issue by hashharvest** [samcragg/sharpkml#22]
Is there a way to reduce the precision of the KML file for all coordinates?

See https://en.wikipedia.org/wiki/Decimal_degrees#Precision

**Comment by samcragg** [comment]
There's not a build in way, no, as they're stored as floating point numbers.
However, you may want to try serializing them manually and specifying the readable option, which might help reduce the digits of some of the numbers:

```C#
var serializer = new Serializer(SerializerOptions.ReadableFloatingPoints);
serializer.Serialize(kml);
// Use serializer.Xml to get the generated Kml
```
Hope that helps a little (you may be able to round the co-ordinates yourself but, as mentioned, because they're `doubles` it's not straight forward to get a fixed amount of digits unless you want to have ago at changing the serializer to pass in the string format you want).
