### ISSUE TITLE
LoadFromKmz does not exist

### ISSUE THREAD

**Issue by jsgoupil** [samcragg/sharpkml#26]
https://github.com/samcragg/sharpkml/blob/master/docs/ExtractingInformation.md

says to use `LoadFromKmz` but that doesn't exist.
Do you mind to explain how to use it and update the doc?

Thanks!

**Comment by jsgoupil** [comment]
I used IL Spy, and I think it should use `GetDefaultKmlFile()`

**Comment by samcragg** [comment]
Sorry about that confusion and thanks for poointing that out; you are correct, the `GetDefaultKmlFile` is the method you want.

Originally the Kmz handling was done separately from the Kml handling (due to dependencies on third party compression libraries), however, since moving to dotnet standard it's all in the same package and looks like I forgot to update the documentation with the changes.

Thanks again for reporting, the documentation should be up to date now.

**Comment by jsgoupil** [comment]
Are you sure the whole documentation is up to date? I don't recall seeing Flatten().

**Comment by samcragg** [comment]
It's actually an extension method (see [ElementExtensions](https://github.com/samcragg/sharpkml/blob/master/SharpKml/Engine/ElementExtensions.cs#L52)), so to use it you'll need a `using SharpKml.Engine` at the top of the file (as mentioned in the comments in the code snippet).

If you do spot something else though or feel that the documentation is still confusing then please feel free to raise another issue/PR and we can improve it :slightly_smiling_face:
