### ISSUE TITLE
Question: Getting area/perimeter

### ISSUE THREAD

**Issue by christmas96** [samcragg/sharpkml#32]
Hello.
Is there any way to get area and perimeter of polygon of Kml?

**Comment by samcragg** [comment]
There isn't at the moment I'm afraid. There are some basic helpers inside [MathHelpers](https://github.com/samcragg/sharpkml/blob/main/SharpKml/Base/MathHelpers.cs), but these are more around connecting two points and, in fiarness, the only reason those helpers are there is because the original C++ library had them.

Unfortunately, after a quick 10 minute search I can't even recommend a library that might be able to help you. If you do find one, or find some simple algorithms you think should be incorporated in this library, then please let me know and I'll see how easy they would be to add to this library.

Please let me know how you get on, sorry I couldn't help more.

**Comment by christmas96** [comment]
Thank you for responce.
