### ISSUE TITLE
other number format not supported

### ISSUE THREAD

**Issue by ehsangfl** [samcragg/sharpkml#34]
Hi
a point as placemark on kml file, if coordinate numbers was
 ```
     <Point>
        <extrude>0</extrude><altitudeMode>clampToGround</altitudeMode>
        <coordinates> 48.30213500023012,31.00159099982483,0</coordinates>
      </Point>
```
parser parsed it on Coordinate property of point object, but if numbers has localised format, like
 ```
     <Point>
        <extrude>0</extrude><altitudeMode>clampToGround</altitudeMode>
        <coordinates> 48/30213500023012,31/00159099982483,0</coordinates>
      </Point>
```
Parser cannot pars it and Coordinate property is null.
a simple solution, is to add a default parameter of IFormatter type to KmlFile.Load() function , that we can pass a culture to it.
BR

**Comment by samcragg** [comment]
Thanks for the suggestion and appologies if you're running into difficulties because of this.

Unfortunately, I'm not sure it's something that the library can support, as the KML specification (section 16.9) specifies the coordinates as a:

> String representing one or more coordinate tuples, with each tuple consisting of decimal values for geodetic longitude, geodetic latitude, and altitude. The altitude component is optional. The coordinate separator is a comma and the tuple separator is a whitespace. Longitude and latitude coordinates are expressed in decimal degrees only.

Here decimal refers to the XML definition of [decimal](https://www.w3.org/TR/xmlschema-2/#decimal):

> decimal has a lexical representation consisting of a finite-length sequence of decimal digits (#x30-#x39) separated by a period as a decimal indicator.

Therefore, the local culture information doesn't seem to be able to be taken into account. If the library _was_ to support it as an extension, I'm not sure how it would work with cultures that use a comma as a decimal separator, as the comma is used to separate the values inside the tuple (e.g. how would 1,2,3 be parsed?) Because of this, I don't think there's an easy solution to the problem unfortunately.
